name: Test Bundlesize checks

# Controls when the workflow will run
on:
  pull_request:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check-build-size:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-node@v2
        with:
          node-version: "12.11.1"

      - name: Install node packages and build
        run: |
          yarn
          yarn build

      - name: Get commit message
        run: |
          echo "COMMIT_MESSAGE<<EOF" >> $GITHUB_ENV
          echo "$(git log --format=%B -n 1 HEAD)" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Check bundlesize
        env:
          BUNDLESIZE_GITHUB_TOKEN: ${{ secrets.BUNDLESIZE_GITHUB_TOKEN }}
          CI_REPO_OWNER: ${{ github.repository_owner }}
          CI_REPO_NAME: bundlesize-test
          CI_COMMIT_MESSAGE: ${{ env.COMMIT_MESSAGE }}
          CI_COMMIT_SHA: ${{ github.sha }}
          CI: true
        run: yarn bundlesize
