name: Test Bundlesize checks

# Controls when the workflow will run
on:
  pull_request:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  check-build-size:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-node@v2
        with:
          node-version: "12.11.1"

      - name: Install node packages and build
        run: |
          yarn
          yarn build

      - name: Check bundlesize
        run: yarn bundlesize > result.md

      - name: Edit result file
        run: sed -e '1d' -e '$d' result.md > bundlesize-report.md

      - name: Store file
        id: bundlesize-report
        uses: chuhlomin/render-template@v1.2
        with:
          template: ./bundlesize-report.md

      - name: Add comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.number }}
          body: ${{ steps.bundlesize-report.outputs.result }}
